### ISSUE TITLE
Calculadora permite divisão por 0

### ISSUE THREAD

**Issue by JCDMeira** [vieira-a/tip-calculator#1]
- [x] Travar condição de 0 pessoas como inválida
- [x] Não deixar aparecer NaN

![image](https://user-images.githubusercontent.com/65555624/183292093-d8e67bf1-841f-4a59-9c8f-281f37058545.png)

**Comment by vieira-a** [comment]
Após um tempo de estudo e aquisição de novos conhecimentos, estou voltando ao projeto para refatorar e aplicar melhorias.
Aqui está uma delas:

**Nova função para validar o valor da gorjeta capturado. 
Esta função será utilizada para mais validações antes do calculo final.**

```
function validationBill() {
  if(billValue === 0 ) {
    billValidation.textContent = validationText
  } else {
    billValidation.textContent = " "
  }
}
```

**Nova função para capturar o valor da gorjeta, aplicando função anterior para validação**
```
function getBillValue() {
  billElement.addEventListener('change', function(){
    billValue = Number(billElement.value)
    validationBill()
  }
)}
```
Com isso será possível evitar o calculo indevido.

Link para a lista de alterações e melhorias que desejo aplicar a este projeto:
[Refatoração e melhorias](https://github.com/vieira-a/tip-calculator/blob/main/REFACTORY.md)
