### ISSUE TITLE
Adicionar o que aprendeu com o projeto no readme

### ISSUE THREAD

**Issue by JCDMeira** [vieira-a/tip-calculator#2]
Nos projetos do front-end tem uma parte o que aprendi, acho essa parte bem interessante e com certeza vai enriquecer seu projeto.

Enfatiza pelo menos uns 2~3 pontos que achou interessante nesse projeto.

**Comment by vieira-a** [comment]
Concluí a versão 2.0 do projeto aplicando as melhorias propostas. 
O README agora conta com uma seção aonde abordo os principais aprendizados.
Muito obrigado!
